### ISSUE TITLE
Roadmap to kraken 2.0

### ISSUE THREAD

**Issue by jasisk** [krakenjs/kraken-js#324]
- [x] identify and document updated owned dependencies
  - [x] [confit 2.0.3](https://github.com/krakenjs/confit/tree/v2.0.3) ([documented](https://github.com/krakenjs/confit/releases/tag/v2.0.0))
  - [x] [middleware 3.0.1](https://github.com/krakenjs/meddleware/tree/v3.0.1) ([documented](https://github.com/krakenjs/meddleware/releases))
- [x] identify updated unowned minimum dependencies
- [x] clearly identify additional changes within core
- [x] write migratory documentation (consider a static analyzer)
- [x] update readme
- [ ] update example apps (tracked by #___)
- [ ] update website (tracked by #___)

**Comment by lmarkus** [comment]
Two-dot-oh.  Nice. 
Is there an approx. timeline for this?

**Comment by jasisk** [comment]
I plead the 0.12th.

**Comment by ohNegative** [comment]
Will something dealing with backwards compatibility will be included in any changes happening with the core?

**Comment by jasisk** [comment]
The changes from 1.0 to 2.0 aren't terribly dramatic—in fact, the surface for kraken itself will remain the same. Some of the dependencies have changed their default behaviors in a few smaller cases which is why we need a "major" bump. A significant portion of users won't have to change much if anything at all. Those that will have to make changes can expect a migration guide.

**Comment by ohNegative** [comment]
As a nervous AngularJS developer, I thank you for explaining that to me.

**Comment by jasisk** [comment]
My pleasure.

Our 1.0 to 2.0 should be a walk in the park compared to Angular. Of course, I imagine most thing are. ;)

**Comment by pvenkatakrishnan** [comment]
also add bumping confit to this list
